//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperationWithAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetIPMethodCall
    {
        public int GetIPID { get; set; }
        public string MethodName { get; set; }
        public string CallerIP { get; set; }
        public System.DateTime CallingTime { get; set; }
    }
}
